package sanakirjaM;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.07.22 02:50:38 // Generated by ComTest
 *
 */
public class RelaatiotTest {



  // Generated by ComTest BEGIN
  /** testLisaa32 */
  @Test
  public void testLisaa32() {    // Relaatiot: 32
    Relaatiot relaatiot = new Relaatiot(); 
    Relaatio rel1 = new Relaatio(), rel2 = new Relaatio(); 
    assertEquals("From: Relaatiot line: 35", 0, relaatiot.getLkm()); 
    relaatiot.lisaa(rel1); assertEquals("From: Relaatiot line: 36", 1, relaatiot.getLkm()); 
    relaatiot.lisaa(rel2); assertEquals("From: Relaatiot line: 37", 2, relaatiot.getLkm()); 
    relaatiot.lisaa(rel1); assertEquals("From: Relaatiot line: 38", 3, relaatiot.getLkm()); 
    relaatiot.lisaa(rel1); assertEquals("From: Relaatiot line: 39", 4, relaatiot.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaRekisterit51 */
  @Test
  public void testAnnaRekisterit51() {    // Relaatiot: 51
    Relaatiot relaatiot = new Relaatiot(); 
    Sana koira1 = new Sana(), koira2 = new Sana(), koira3 = new Sana(); 
    koira1.rekisteroi(); koira2.rekisteroi(); koira3.rekisteroi(); 
    int sid1 = koira1.getSid(); 
    int sid2 = koira2.getSid(); 
    Rekisteri rek1 = new Rekisteri(), rek2 = new Rekisteri(), rek3 = new Rekisteri(); 
    int rid1 = rek1.rekisteroi(); 
    int rid2 = rek2.rekisteroi(); 
    int rid3 = rek3.rekisteroi(); 
    Relaatio rel1 = new Relaatio(sid1, rid1); 
    Relaatio rel2 = new Relaatio(sid1, rid2); 
    Relaatio rel3 = new Relaatio(sid2, rid3); 
    relaatiot.lisaa(rel1); 
    relaatiot.lisaa(rel2); 
    relaatiot.lisaa(rel3); 
    List<Relaatio> loydetyt; 
    loydetyt = relaatiot.annaRekisterit(sid1); 
    assertEquals("From: Relaatiot line: 70", 2, loydetyt.size()); 
    loydetyt = relaatiot.annaRekisterit(sid2); 
    assertEquals("From: Relaatiot line: 72", 1, loydetyt.size()); 
  } // Generated by ComTest END
}