package sanakirjaM;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.07.21 15:52:25 // Generated by ComTest
 *
 */
public class RelaatioTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi91 */
  @Test
  public void testRekisteroi91() {    // Relaatio: 91
    Relaatio rel1 = new Relaatio(); 
    assertEquals("From: Relaatio line: 93", 0, rel1.getIdNro()); 
    rel1.rekisteroi(); 
    Relaatio rel2 = new Relaatio(); 
    rel2.rekisteroi(); 
    int n1 = rel1.getIdNro(); 
    int n2 = rel2.getIdNro(); 
    assertEquals("From: Relaatio line: 99", n2-1, n1); 
  } // Generated by ComTest END
}