package sanakirjaM;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.07.21 17:20:20 // Generated by ComTest
 *
 */
public class SanatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa29 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa29() throws SailoException {    // Sanat: 29
    Sanat sanat = new Sanat(); 
    Sana koira1 = new Sana(), koira2 = new Sana(); 
    assertEquals("From: Sanat line: 33", 0, sanat.getLkm()); 
    sanat.lisaa(koira1); assertEquals("From: Sanat line: 34", 1, sanat.getLkm()); 
    sanat.lisaa(koira2); assertEquals("From: Sanat line: 35", 2, sanat.getLkm()); 
    sanat.lisaa(koira1); assertEquals("From: Sanat line: 36", 3, sanat.getLkm()); 
    assertEquals("From: Sanat line: 37", koira1, sanat.anna(0)); 
    assertEquals("From: Sanat line: 38", koira2, sanat.anna(1)); 
    assertEquals("From: Sanat line: 39", koira1, sanat.anna(2)); 
    assertEquals("From: Sanat line: 40", false, sanat.anna(1) == koira1); 
    assertEquals("From: Sanat line: 41", true, sanat.anna(1) == koira2); 
    try {
    assertEquals("From: Sanat line: 42", koira1, sanat.anna(3)); 
    fail("Sanat: 42 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    sanat.lisaa(koira1); assertEquals("From: Sanat line: 43", 4, sanat.getLkm()); 
    sanat.lisaa(koira1); assertEquals("From: Sanat line: 44", 5, sanat.getLkm()); 
    try {
    sanat.lisaa(koira1); 
    fail("Sanat: 45 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}